# Generated by Django 6.0 on 2025-12-24 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aisle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(help_text="e.g. 'A', 'B'", max_length=10)),
                ('start_x', models.FloatField()),
                ('start_z', models.FloatField()),
                ('length', models.FloatField(help_text='Length of the aisle')),
                ('width', models.FloatField(default=2.0)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('position_on_shelf', models.FloatField()),
                ('width', models.FloatField(default=0.4)),
                ('height', models.FloatField(default=0.4)),
                ('depth', models.FloatField(default=0.4)),
                ('color', models.CharField(default='#ff0000', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('width', models.FloatField(help_text='X-axis size')),
                ('depth', models.FloatField(help_text='Z-axis size')),
                ('height', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='MovementJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_x', models.FloatField()),
                ('start_z', models.FloatField()),
                ('end_x', models.FloatField()),
                ('end_z', models.FloatField()),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.item')),
            ],
        ),
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=20)),
                ('pos_x', models.FloatField()),
                ('pos_z', models.FloatField()),
                ('rotation', models.FloatField(default=0)),
                ('width', models.FloatField(default=1.5)),
                ('depth', models.FloatField(default=0.5)),
                ('height', models.FloatField(default=3.0)),
                ('aisle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='racks', to='core.aisle')),
            ],
        ),
        migrations.CreateModel(
            name='Shelf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=20)),
                ('level_height', models.FloatField(help_text='Height from floor in meters')),
                ('rack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shelves', to='core.rack')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='shelf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.shelf'),
        ),
        migrations.CreateModel(
            name='Conveyor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('start_x', models.FloatField()),
                ('start_z', models.FloatField()),
                ('end_x', models.FloatField()),
                ('end_z', models.FloatField()),
                ('speed', models.FloatField(default=1.0)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conveyors', to='core.warehouse')),
            ],
        ),
        migrations.AddField(
            model_name='aisle',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aisles', to='core.warehouse'),
        ),
    ]
