# Generated by Django 6.0 on 2025-12-24 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=20)),
                ('pos_x', models.FloatField()),
                ('pos_z', models.FloatField()),
                ('rotation', models.FloatField(default=0)),
                ('width', models.FloatField(default=2.0)),
                ('depth', models.FloatField(default=1.0)),
                ('height', models.FloatField(default=3.0)),
                ('shelves', models.IntegerField(default=4)),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('width', models.FloatField(help_text='X-axis size in meters')),
                ('depth', models.FloatField(help_text='Z-axis size in meters')),
                ('height', models.FloatField(help_text='Y-axis ceiling height')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('shelf_level', models.IntegerField()),
                ('position_on_shelf', models.FloatField()),
                ('width', models.FloatField(default=0.5)),
                ('height', models.FloatField(default=0.5)),
                ('depth', models.FloatField(default=0.5)),
                ('color', models.CharField(default='#ff0000', max_length=7)),
                ('rack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.rack')),
            ],
        ),
        migrations.AddField(
            model_name='rack',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='racks', to='core.warehouse'),
        ),
    ]
