# Generated by Django 6.0 on 2025-12-24 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conveyor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('start_x', models.FloatField()),
                ('start_z', models.FloatField()),
                ('end_x', models.FloatField()),
                ('end_z', models.FloatField()),
                ('speed', models.FloatField(default=1.0)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conveyors', to='core.warehouse')),
            ],
        ),
    ]
