# Generated by Django 6.0 on 2025-12-24 23:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_order_orderitem_wave'),
    ]

    operations = [
        migrations.CreateModel(
            name='Road',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos_x', models.FloatField()),
                ('pos_z', models.FloatField()),
                ('width', models.FloatField(default=2.0)),
                ('depth', models.FloatField(default=2.0)),
                ('rotation', models.FloatField(default=0.0)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roads', to='core.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(default='#007bff', max_length=20)),
                ('pos_x', models.FloatField()),
                ('pos_z', models.FloatField()),
                ('width', models.FloatField(default=10.0)),
                ('depth', models.FloatField(default=10.0)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='core.warehouse')),
            ],
        ),
    ]
