# Generated by Django 6.0 on 2025-12-24 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_conveyor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='depth',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='height',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='width',
            field=models.FloatField(),
        ),
        migrations.CreateModel(
            name='MovementJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_x', models.FloatField()),
                ('start_z', models.FloatField()),
                ('end_x', models.FloatField()),
                ('end_z', models.FloatField()),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.item')),
            ],
        ),
    ]
